# DEPRECATED: AI Consulting Deployment Workflow
# 
# This workflow has been deprecated and replaced with the unified deployment workflow.
# All AI consulting functionality is now handled by the main deploy.yml workflow.
# 
# The issues with this workflow were:
# 1. Missing production environment in wrangler.toml
# 2. Inconsistent secret naming (CLOUDFLARE_API_TOKEN vs CF_API_TOKEN)
# 3. Redundant deployment steps
# 4. Overly complex build process
# 
# The new unified workflow (.github/workflows/deploy.yml) provides:
# ✅ Proper environment handling (staging/production)
# ✅ Consistent secret management
# ✅ Simplified deployment process
# ✅ Better error handling and testing
# ✅ Security scanning
# 
# To use the new workflow:
# 1. Ensure all secrets use the standardized names (CF_API_TOKEN, CF_ACCOUNT_ID, etc.)
# 2. Push changes to main branch for production deployment
# 3. Create pull requests for staging deployment
# 
# This file is kept for historical reference and will be removed in a future commit.

name: Deprecated AI Consulting Deployment
on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'This workflow is deprecated. Use the main deploy.yml workflow instead.'
        required: false
        default: 'deprecated'

jobs:
  deprecated-notice:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "❌ This workflow has been deprecated."
          echo "✅ Please use the main deployment workflow: .github/workflows/deploy.yml"
          echo "📖 The new workflow handles all deployment scenarios including AI consulting functionality."
          exit 1 